"""initial schema

Revision ID: 93cd8044d35d
Revises: 
Create Date: 2026-08-10 16:08:46.481801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93cd8044d35d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('crm_contact_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_crm_contact_id'), 'contacts', ['crm_contact_id'], unique=False)
    op.create_index(op.f('ix_contacts_phone'), 'contacts', ['phone'], unique=False)
    op.create_index(op.f('ix_contacts_tg_user_id'), 'contacts', ['tg_user_id'], unique=True)
    op.create_table('managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('b24_user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('manager', 'supervisor', name='managerrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_managers_b24_user_id'), 'managers', ['b24_user_id'], unique=True)
    op.create_table('dialogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('messenger', sa.Enum('tg', 'max', name='messenger'), nullable=False),
    sa.Column('external_chat_id', sa.String(length=128), nullable=False),
    sa.Column('crm_deal_id', sa.Integer(), nullable=True),
    sa.Column('crm_entity_type', sa.String(length=32), nullable=True),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='dialogstatus'), nullable=False),
    sa.Column('last_msg_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dialogs_contact_id'), 'dialogs', ['contact_id'], unique=False)
    op.create_index(op.f('ix_dialogs_crm_deal_id'), 'dialogs', ['crm_deal_id'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['managers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tg_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('session_path', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('active', 'banned', 'offline', name='tgaccountstatus'), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('last_floodwait_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manager_id')
    )
    op.create_index(op.f('ix_tg_accounts_phone'), 'tg_accounts', ['phone'], unique=True)
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dialog_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('in', 'out', name='messagedirection'), nullable=False),
    sa.Column('tg_message_id', sa.BigInteger(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'sent', 'delivered', 'read', 'error', name='messagestatus'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('author_user_id', sa.Integer(), nullable=True),
    sa.Column('timeline_comment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dialog_id'], ['dialogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_dialog_id'), 'messages', ['dialog_id'], unique=False)
    op.create_index(op.f('ix_messages_tg_message_id'), 'messages', ['tg_message_id'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('photo', 'file', 'video', 'voice', 'sticker', name='attachmenttype'), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outbox',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dialog_id', sa.Integer(), nullable=False),
    sa.Column('tg_account_id', sa.Integer(), nullable=False),
    sa.Column('external_chat_id', sa.String(length=128), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('attachment_id', sa.Integer(), nullable=True),
    sa.Column('is_initiation', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'sending', 'sent', 'failed', 'retrying', name='outboxstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_error', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], ),
    sa.ForeignKeyConstraint(['dialog_id'], ['dialogs.id'], ),
    sa.ForeignKeyConstraint(['tg_account_id'], ['tg_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_dialog_id'), 'outbox', ['dialog_id'], unique=False)
    op.create_index(op.f('ix_outbox_next_attempt_at'), 'outbox', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_outbox_status'), 'outbox', ['status'], unique=False)
    op.create_index(op.f('ix_outbox_tg_account_id'), 'outbox', ['tg_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_tg_account_id'), table_name='outbox')
    op.drop_index(op.f('ix_outbox_status'), table_name='outbox')
    op.drop_index(op.f('ix_outbox_next_attempt_at'), table_name='outbox')
    op.drop_index(op.f('ix_outbox_dialog_id'), table_name='outbox')
    op.drop_table('outbox')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_messages_tg_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_dialog_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_tg_accounts_phone'), table_name='tg_accounts')
    op.drop_table('tg_accounts')
    op.drop_table('templates')
    op.drop_index(op.f('ix_dialogs_crm_deal_id'), table_name='dialogs')
    op.drop_index(op.f('ix_dialogs_contact_id'), table_name='dialogs')
    op.drop_table('dialogs')
    op.drop_index(op.f('ix_managers_b24_user_id'), table_name='managers')
    op.drop_table('managers')
    op.drop_index(op.f('ix_contacts_tg_user_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_phone'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_crm_contact_id'), table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
